### ISSUE TITLE
Unable to fetch contract object

### ISSUE THREAD

**Issue by trilade** [NoahZinsmeister/web3-webpacked#2]
Hello,

I have been successful to fetch contract balances, and eth network info via a localy hosted webpage based on your guide.
Everything seem to be loading fine:
`Initializing web3 upon page load.
(index):34 web3 initialized.
(index):46 Network switched from undefined to 42.
(index):53 Primary account switched from undefined to 0x1529962829e7B13280CA022026627c0588C1e31d.`

But when I'm trying to fetch the owner of a contract by running the following in Chrome console:
`var ABI = [
	{
		"inputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "owner",
		"outputs": [
			{
				"name": "",
				"type": "address"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
]
var options = ""
var contractAddress = "0xbbf2fb8862cf1fc6697841b290b35114381c3995"
console.log(w3w.getContract(ABI,contractAddress,options));`

It doesnt seem to return the requested data.
Chrome console comes back with something like:
`E {_requestManager: t, givenProvider: MetamaskInpageProvider, providers: {…}, _provider: MetamaskInpageProvider, …}`

And if I open it I can see an error:
`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.remoteFunction (<anonymous>:2:14)`

Not sure what I'm doing wrong - could you please advise?

Many thanks

**Comment by NoahHydro** [comment]
Hey there, I didn't have a problem running this code. Your contract object should look like `Contract {_requestManager: RequestManager, givenProvider: MetamaskInpageProvider, providers: {…}, _provider: MetamaskInpageProvider, …}`. Are you sure that you're on the right network for accessing that contract?

Also, don't pass `options` as an empty string, leave it `undefined`.

**Comment by NoahZinsmeister** [comment]
Glad you figured this out! Fee free to open another issue if you have any more problems :)
